#!/usr/bin/env python3
"""tp2b compiler and FPGA runtime generator for Knot-8 v4.

The packed and native backends execute the tp2b FSM, tape, loops, and output
on Knot-8.  The const backend is retained as an optional whole-program
optimization and reference evaluator.
"""

from __future__ import annotations

import argparse
import collections
import pathlib
import sys
import tempfile
from dataclasses import dataclass

from knot8asm import AssemblyError, assemble


CANONICAL_TAPE_SIZE = 30_000
DEFAULT_MAX_STEPS = 10_000_000


class CompileError(Exception):
    pass


@dataclass(frozen=True)
class Command:
    value: str
    line: int
    column: int


@dataclass(frozen=True)
class EvaluationResult:
    output: bytes
    steps: int
    final_pc: int
    final_state: int
    final_pointer: int
    terminated_by_unmatched_jump: bool


def parse_source(text: str) -> tuple[list[Command], dict[int, int]]:
    commands: list[Command] = []
    line = 1
    column = 0
    for character in text:
        if character == "\n":
            line += 1
            column = 0
            continue
        column += 1
        if character in {"(", "L"}:
            commands.append(Command(character, line, column))

    pairs: dict[int, int] = {}
    stack: list[int] = []
    for index, command in enumerate(commands):
        if command.value == "(":
            stack.append(index)
        elif stack:
            opening = stack.pop()
            pairs[opening] = index
            pairs[index] = opening
    return commands, pairs


def evaluate(
    commands: list[Command],
    pairs: dict[int, int],
    *,
    tape_size: int = CANONICAL_TAPE_SIZE,
    max_steps: int = DEFAULT_MAX_STEPS,
) -> EvaluationResult:
    if tape_size < 1:
        raise CompileError("tape size must be positive")
    if max_steps < 1:
        raise CompileError("max steps must be positive")

    tape = bytearray(tape_size)
    output = bytearray()
    pc = 0
    pointer = 0
    state = 0
    steps = 0
    unmatched_exit = False

    while pc < len(commands):
        if steps >= max_steps:
            command = commands[pc]
            raise CompileError(
                "program did not terminate within "
                f"{max_steps} commands; stopped at command {pc}, "
                f"source {command.line}:{command.column}, S{state}"
            )
        steps += 1
        command = commands[pc].value

        if command == "(":
            if state == 0:
                pointer = (pointer + 1) % tape_size
                state = 1
                pc += 1
            elif state == 1:
                state = 2
                if tape[pointer] == 0:
                    if pc not in pairs:
                        unmatched_exit = True
                        break
                    pc = pairs[pc] + 1
                else:
                    pc += 1
            elif state == 2:
                state = 0
                if tape[pointer] == 0:
                    if pc not in pairs:
                        unmatched_exit = True
                        break
                    pc = pairs[pc] + 1
                else:
                    pc += 1
            else:
                state = 0
                pc += 1
        else:
            if state == 0:
                pointer = (pointer - 1) % tape_size
                state = 2
                pc += 1
            elif state == 1:
                tape[pointer] = (tape[pointer] + 1) & 0xFF
                state = 3
                pc += 1
            elif state == 2:
                state = 1
                if tape[pointer] != 0:
                    if pc not in pairs:
                        unmatched_exit = True
                        break
                    pc = pairs[pc]
                else:
                    pc += 1
            else:
                output.append(tape[pointer])
                state = 0
                pc += 1

    return EvaluationResult(
        output=bytes(output),
        steps=steps,
        final_pc=pc,
        final_state=state,
        final_pointer=pointer,
        terminated_by_unmatched_jump=unmatched_exit,
    )


def _format_byte_rows(values: bytes, width: int = 16) -> list[str]:
    rows: list[str] = []
    for start in range(0, len(values), width):
        chunk = values[start : start + width]
        rows.append("        .byte " + ", ".join(f"0x{value:02X}" for value in chunk))
    return rows


def generate_knot8_assembly(result: EvaluationResult, source_name: str) -> str:
    output = result.output
    header = [
        "; Generated by tp2bc for Knot-8 v4.",
        f"; Source: {source_name}",
        f"; Compile-time tp2b commands executed: {result.steps}",
        f"; Output bytes: {len(output)}",
        "",
    ]
    if not output:
        return "\n".join(header + ["        HALT", ""])
    if len(output) > 0xFFFF:
        raise CompileError("Knot-8 output backend supports at most 65535 bytes")

    low_count = len(output) & 0xFF
    high_count = (len(output) >> 8) & 0xFF
    body = [
        f"        LOADI   R0, 0x{low_count:02X}",
        f"        LOADI   R1, 0x{high_count:02X}",
        "        LOADI_H HIGH(output_data)",
        "        LOADI_L LOW(output_data)",
        "        SWAPXY",
        "        LOADI_H 0xFF",
        "        LOADI_L 0x03",
        "        SWAPXY                  ; IDX=output, IDY=UART status",
        "",
        "output_loop:",
        "        LOAD_INC R2",
        "        SWAPXY                  ; IDX=UART status, IDY=output",
        "uart_wait:",
        "        LOAD    R3, [IDX]",
        "        CMPI    R3, 1",
        "        BRNZ    uart_wait",
        "        DEC_IDX                 ; FF03 -> FF02",
        "        STORE   R2, [IDX]",
        "        INC_IDX                 ; restore FF03",
        "        SWAPXY                  ; IDX=output, IDY=UART status",
        "        SUBI    R0, 1",
        "        SBCI    R1, 0",
        "        CMPI    R0, 0",
        "        CPCI    R1, 0",
        "        BRNZ    output_loop",
        "        HALT",
        "",
        "output_data:",
    ]
    return "\n".join(header + body + _format_byte_rows(output) + [""])


def _native_successors(
    pc: int,
    state: int,
    commands: list[Command],
    pairs: dict[int, int],
) -> tuple[int, ...]:
    end = len(commands)
    command = commands[pc].value
    following = min(pc + 1, end)
    if command == "(":
        if state == 0:
            return (following, 1)
        if state in {1, 2}:
            after_match = min(pairs.get(pc, end) + 1, end)
            next_state = 2 if state == 1 else 0
            return (following, next_state, after_match, next_state)
        return (following, 0)
    if state == 0:
        return (following, 2)
    if state == 1:
        return (following, 3)
    if state == 2:
        matching = pairs.get(pc, end)
        return (following, 1, matching, 1)
    return (following, 0)


def _reachable_native_nodes(
    commands: list[Command], pairs: dict[int, int]
) -> list[tuple[int, int]]:
    if not commands:
        return []
    queue: collections.deque[tuple[int, int]] = collections.deque([(0, 0)])
    seen: set[tuple[int, int]] = set()
    while queue:
        node = queue.popleft()
        pc, state = node
        if pc >= len(commands) or node in seen:
            continue
        seen.add(node)
        successors = _native_successors(pc, state, commands, pairs)
        for index in range(0, len(successors), 2):
            successor = (successors[index], successors[index + 1])
            if successor[0] < len(commands) and successor not in seen:
                queue.append(successor)
    return sorted(seen)


def generate_native_knot8_assembly(
    commands: list[Command],
    pairs: dict[int, int],
    source_name: str,
) -> str:
    """Specialize the tp2b FSM into native Knot-8 control-flow blocks."""

    nodes = _reachable_native_nodes(commands, pairs)
    labels = {node: f"tp_pc_{node[0]:04X}_s{node[1]}" for node in nodes}

    def target_label(pc: int, state: int) -> str:
        return labels.get((pc, state), "tp_exit")

    lines = [
        "; Generated by tp2bc --backend native for Knot-8 v4.",
        f"; Source: {source_name}",
        f"; tp2b commands: {len(commands)}",
        "; FSM state is specialized into control-flow labels; tape remains live.",
        "; Knot target profile: 16384 wrapping byte cells at 8000-BFFF.",
        "",
        "        LOADI_H 0xFF",
        "        LOADI_L 0x02",
        "        SWAPXY                  ; IDY=UART TX, IDX=0",
        "        LOADI_H 0x80",
        "        LOADI_L 0x00            ; IDX=tape cell 0",
    ]
    if nodes:
        lines.append(f"        JUMP_REL {labels[nodes[0]]}")
    else:
        lines.append("        JUMP_REL tp_exit")
    lines.append("")

    for node_index, (pc, state) in enumerate(nodes):
        next_layout = nodes[node_index + 1] if node_index + 1 < len(nodes) else None
        next_layout_label = labels.get(next_layout)
        label = labels[(pc, state)]
        command = commands[pc].value
        following = min(pc + 1, len(commands))
        lines.append(f"{label}:                ; {command} in S{state}")

        def emit_jump(target_pc: int, target_state: int) -> None:
            destination = target_label(target_pc, target_state)
            if destination == "tp_exit":
                lines.append("        HALT")
                return
            if destination != next_layout_label:
                lines.append(f"        JUMP_REL {destination}")

        def emit_zero_branch(
            zero_pc: int,
            zero_state: int,
            nonzero_pc: int,
            nonzero_state: int,
        ) -> None:
            zero_label = target_label(zero_pc, zero_state)
            nonzero_label = target_label(nonzero_pc, nonzero_state)
            lines.extend(["        LOAD    R0, [IDX]", "        CMPI    R0, 0"])
            if zero_label == "tp_exit" and nonzero_label == "tp_exit":
                lines.append("        HALT")
                return
            if zero_label == "tp_exit":
                lines.append(f"        BRNZ    {nonzero_label}")
                lines.append("        HALT")
                return
            if nonzero_label == "tp_exit":
                lines.append(f"        BRZ     {zero_label}")
                lines.append("        HALT")
                return
            if nonzero_label == next_layout_label:
                lines.append(f"        BRZ     {zero_label}")
            elif zero_label == next_layout_label:
                lines.append(f"        BRNZ    {nonzero_label}")
            else:
                lines.append(f"        BRZ     {zero_label}")
                lines.append(f"        JUMP_REL {nonzero_label}")

        if command == "(":
            if state == 0:
                wrap_label = f"{label}_inc_ok"
                lines.extend(
                    [
                        "        INC_IDX",
                        "        GETIDX_H R0",
                        "        CMPI    R0, 0xC0",
                        f"        BRNZ    {wrap_label}",
                        "        LOADI_H 0x80",
                        "        LOADI_L 0x00",
                        f"{wrap_label}:",
                    ]
                )
                emit_jump(following, 1)
            elif state == 1:
                emit_zero_branch(
                    min(pairs.get(pc, len(commands)) + 1, len(commands)),
                    2,
                    following,
                    2,
                )
            elif state == 2:
                emit_zero_branch(
                    min(pairs.get(pc, len(commands)) + 1, len(commands)),
                    0,
                    following,
                    0,
                )
            else:
                emit_jump(following, 0)
        else:
            if state == 0:
                wrap_label = f"{label}_dec_ok"
                lines.extend(
                    [
                        "        DEC_IDX",
                        "        GETIDX_H R0",
                        "        CMPI    R0, 0x7F",
                        f"        BRNZ    {wrap_label}",
                        "        LOADI_H 0xBF",
                        "        LOADI_L 0xFF",
                        f"{wrap_label}:",
                    ]
                )
                emit_jump(following, 2)
            elif state == 1:
                lines.append("        INC_MEM [IDX]")
                emit_jump(following, 3)
            elif state == 2:
                emit_zero_branch(
                    following,
                    1,
                    pairs.get(pc, len(commands)),
                    1,
                )
            else:
                wait_label = f"{label}_uart_wait"
                lines.extend(
                    [
                        "        LOAD    R1, [IDX]",
                        "        SWAPXY                  ; IDX=UART TX, IDY=tape",
                        "        INC_IDX                 ; FF02 -> FF03 status",
                        f"{wait_label}:",
                        "        LOAD    R0, [IDX]",
                        "        CMPI    R0, 1",
                        f"        BRNZ    {wait_label}",
                        "        DEC_IDX                 ; FF03 -> FF02 data",
                        "        STORE   R1, [IDX]",
                        "        SWAPXY                  ; IDX=tape, IDY=UART TX",
                    ]
                )
                emit_jump(following, 0)
        lines.append("")

    lines.extend(["tp_exit:", "        HALT", ""])
    return "\n".join(lines)


def _pack_2bit_program(commands: list[Command]) -> bytes:
    """Pack BOF, tp2b commands, and EOF as four 2-bit tokens per byte."""

    token_values = [3]
    token_values.extend(0 if command.value == "(" else 1 for command in commands)
    token_values.append(2)
    packed = bytearray((len(token_values) + 3) // 4)
    for index, value in enumerate(token_values):
        packed[index // 4] |= value << (2 * (index % 4))
    return bytes(packed)


def generate_packed_knot8_assembly(
    commands: list[Command],
    source_name: str,
) -> str:
    """Generate a compact on-FPGA tp2b bytecode interpreter.

    Token values are 00='(', 01='L', 10=EOF, and 11=BOF.  BOF/EOF make
    unmatched loop scans terminate exactly as the canonical interpreter does.
    The interpreter reserves eight bytes below the initial stack pointer and
    uses the remaining 16,376 data-RAM bytes as a wrapping tape.
    """

    packed = _pack_2bit_program(commands)
    lines = [
        "; Generated by tp2bc --backend packed for Knot-8 v4.",
        f"; Source: {source_name}",
        f"; tp2b commands: {len(commands)}",
        f"; Packed 2-bit bytecode: {len(packed)} bytes including BOF/EOF.",
        "; FSM, tape, loop scans, and UART output all execute on the FPGA.",
        "; Tape: 8000-BFF7 (16376 wrapping byte cells).",
        "",
    ]
    unique_label = 0

    def emit_goto(target: str) -> None:
        lines.extend(
            [
                f"        LOADI_H HIGH({target})",
                f"        LOADI_L LOW({target})",
                "        JUMP",
            ]
        )

    def emit_far_branch(condition: str, target: str, prefix: str) -> None:
        nonlocal unique_label
        inverse = {
            "BRZ": "BRNZ",
            "BRNZ": "BRZ",
            "BRC": "BRNC",
            "BRNC": "BRC",
        }[condition]
        skip = f"{prefix}_skip_{unique_label}"
        unique_label += 1
        lines.append(f"        {inverse:<7} {skip}")
        emit_goto(target)
        lines.append(f"{skip}:")

    def emit_load_source_pointer() -> None:
        lines.extend(
            [
                "        LOADSP  R0, 0",
                "        SETIDX_H R0",
                "        LOADSP  R0, 1",
                "        SETIDX_L R0",
            ]
        )

    def emit_save_source_pointer() -> None:
        lines.extend(
            [
                "        GETIDX_H R0",
                "        STORESP R0, 0",
                "        GETIDX_L R0",
                "        STORESP R0, 1",
            ]
        )

    def emit_load_tape_pointer() -> None:
        lines.extend(
            [
                "        LOADSP  R0, 2",
                "        SETIDX_H R0",
                "        LOADSP  R0, 3",
                "        SETIDX_L R0",
            ]
        )

    def emit_save_tape_pointer() -> None:
        lines.extend(
            [
                "        GETIDX_H R0",
                "        STORESP R0, 2",
                "        GETIDX_L R0",
                "        STORESP R0, 3",
            ]
        )

    def emit_fetch_token(prefix: str) -> None:
        emit_load_source_pointer()
        lines.extend(
            [
                "        LOAD    R0, [IDX]",
                "        CMPI    R2, 0",
                f"        BRZ     {prefix}_token_ready",
                "        SHR     R0",
                "        SHR     R0",
                "        CMPI    R2, 1",
                f"        BRZ     {prefix}_token_ready",
                "        SHR     R0",
                "        SHR     R0",
                "        CMPI    R2, 2",
                f"        BRZ     {prefix}_token_ready",
                "        SHR     R0",
                "        SHR     R0",
                f"{prefix}_token_ready:",
                "        ANDI    R0, 3",
            ]
        )

    def emit_depth_init() -> None:
        lines.extend(
            [
                "        LOADI   R3, 1",
                "        LOADI   R0, 0",
                "        STORESP R0, 4",
            ]
        )

    lines.extend(
        [
            "        ADJSP   -8             ; BFF8-BFFF are interpreter variables",
            "        LOADI_H HIGH(tp_code)",
            "        LOADI_L LOW(tp_code)",
            "        GETIDX_H R0",
            "        STORESP R0, 0          ; packed source pointer high",
            "        GETIDX_L R0",
            "        STORESP R0, 1          ; packed source pointer low",
            "        LOADI   R0, 0x80",
            "        STORESP R0, 2          ; tape pointer high",
            "        LOADI   R0, 0x00",
            "        STORESP R0, 3          ; tape pointer low",
            "        STORESP R0, 4          ; scan depth high",
            "        LOADI   R1, 0          ; FSM state",
            "        LOADI   R2, 1          ; token after BOF",
        ]
    )
    emit_goto("dispatch")
    lines.append("")

    lines.append("dispatch:")
    emit_fetch_token("dispatch")
    lines.extend(
        [
            "        CMPI    R0, 2",
            "        BRNZ    dispatch_not_eof",
            "        HALT",
            "dispatch_not_eof:",
            "        CMPI    R0, 3",
            "        BRNZ    dispatch_not_bof",
            "        HALT",
            "dispatch_not_bof:",
            "        CMPI    R0, 0",
        ]
    )
    emit_far_branch("BRZ", "handle_open", "dispatch_open")
    emit_goto("handle_l")
    lines.append("")

    lines.append("normal_advance:")
    lines.extend(
        [
            "        ADDI    R2, 1",
            "        CMPI    R2, 4",
            "        BRNZ    normal_advance_done",
            "        LOADI   R2, 0",
        ]
    )
    emit_load_source_pointer()
    lines.append("        INC_IDX")
    emit_save_source_pointer()
    lines.append("normal_advance_done:")
    emit_goto("dispatch")
    lines.append("")

    lines.append("handle_open:")
    lines.extend(["        CMPI    R1, 0"])
    emit_far_branch("BRZ", "open_s0", "open_state0")
    lines.append("        CMPI    R1, 1")
    emit_far_branch("BRZ", "open_s1", "open_state1")
    lines.append("        CMPI    R1, 2")
    emit_far_branch("BRZ", "open_s2", "open_state2")
    lines.append("        LOADI   R1, 0")
    emit_goto("normal_advance")
    lines.append("")

    lines.append("open_s0:")
    emit_load_tape_pointer()
    lines.extend(
        [
            "        INC_IDX",
            "        GETIDX_H R0",
            "        CMPI    R0, 0xBF",
            "        BRNZ    open_s0_no_wrap",
            "        GETIDX_L R0",
            "        CMPI    R0, 0xF8",
            "        BRNZ    open_s0_no_wrap",
            "        LOADI_H 0x80",
            "        LOADI_L 0x00",
            "open_s0_no_wrap:",
        ]
    )
    emit_save_tape_pointer()
    lines.append("        LOADI   R1, 1")
    emit_goto("normal_advance")
    lines.append("")

    lines.append("open_s1:")
    emit_load_tape_pointer()
    lines.extend(["        LOAD    R0, [IDX]", "        CMPI    R0, 0"])
    emit_far_branch("BRZ", "open_s1_zero", "open_s1_test")
    lines.append("        LOADI   R1, 2")
    emit_goto("normal_advance")
    lines.append("open_s1_zero:")
    lines.append("        LOADI   R1, 2")
    emit_depth_init()
    emit_goto("scan_forward_advance")
    lines.append("")

    lines.append("open_s2:")
    emit_load_tape_pointer()
    lines.extend(["        LOAD    R0, [IDX]", "        CMPI    R0, 0"])
    emit_far_branch("BRZ", "open_s2_zero", "open_s2_test")
    lines.append("        LOADI   R1, 0")
    emit_goto("normal_advance")
    lines.append("open_s2_zero:")
    lines.append("        LOADI   R1, 0")
    emit_depth_init()
    emit_goto("scan_forward_advance")
    lines.append("")

    lines.append("handle_l:")
    lines.append("        CMPI    R1, 0")
    emit_far_branch("BRZ", "l_s0", "l_state0")
    lines.append("        CMPI    R1, 1")
    emit_far_branch("BRZ", "l_s1", "l_state1")
    lines.append("        CMPI    R1, 2")
    emit_far_branch("BRZ", "l_s2", "l_state2")
    emit_goto("l_s3")
    lines.append("")

    lines.append("l_s0:")
    emit_load_tape_pointer()
    lines.extend(
        [
            "        DEC_IDX",
            "        GETIDX_H R0",
            "        CMPI    R0, 0x7F",
            "        BRNZ    l_s0_no_wrap",
            "        LOADI_H 0xBF",
            "        LOADI_L 0xF7",
            "l_s0_no_wrap:",
        ]
    )
    emit_save_tape_pointer()
    lines.append("        LOADI   R1, 2")
    emit_goto("normal_advance")
    lines.append("")

    lines.append("l_s1:")
    emit_load_tape_pointer()
    lines.extend(["        INC_MEM [IDX]", "        LOADI   R1, 3"])
    emit_goto("normal_advance")
    lines.append("")

    lines.append("l_s2:")
    emit_load_tape_pointer()
    lines.extend(["        LOAD    R0, [IDX]", "        CMPI    R0, 0"])
    emit_far_branch("BRZ", "l_s2_zero", "l_s2_test")
    lines.append("        LOADI   R1, 1")
    emit_depth_init()
    emit_goto("scan_backward_retreat")
    lines.append("l_s2_zero:")
    lines.append("        LOADI   R1, 1")
    emit_goto("normal_advance")
    lines.append("")

    lines.append("l_s3:")
    emit_load_tape_pointer()
    lines.extend(
        [
            "        LOAD    R3, [IDX]",
            "        LOADI_H 0xFF",
            "        LOADI_L 0x03",
            "l_s3_uart_wait:",
            "        LOAD    R0, [IDX]",
            "        CMPI    R0, 1",
            "        BRNZ    l_s3_uart_wait",
            "        DEC_IDX",
            "        STORE   R3, [IDX]",
            "        LOADI   R1, 0",
        ]
    )
    emit_goto("normal_advance")
    lines.append("")

    lines.append("scan_forward_advance:")
    lines.extend(
        [
            "        ADDI    R2, 1",
            "        CMPI    R2, 4",
            "        BRNZ    scan_forward_fetch",
            "        LOADI   R2, 0",
        ]
    )
    emit_load_source_pointer()
    lines.append("        INC_IDX")
    emit_save_source_pointer()
    lines.append("scan_forward_fetch:")
    emit_fetch_token("scan_forward")
    lines.extend(
        [
            "        CMPI    R0, 2",
            "        BRNZ    scan_forward_not_eof",
            "        HALT                    ; unmatched forward scan",
            "scan_forward_not_eof:",
            "        CMPI    R0, 3",
            "        BRNZ    scan_forward_not_bof",
            "        HALT",
            "scan_forward_not_bof:",
            "        CMPI    R0, 0",
            "        BRNZ    scan_forward_close",
            "        ADDI    R3, 1",
            "        BRNC    scan_forward_inc_done",
            "        LOADSP  R0, 4",
            "        ADDI    R0, 1",
            "        STORESP R0, 4",
            "scan_forward_inc_done:",
        ]
    )
    emit_goto("scan_forward_advance")
    lines.extend(
        [
            "scan_forward_close:",
            "        SUBI    R3, 1",
            "        BRNC    scan_forward_dec_done",
            "        LOADSP  R0, 4",
            "        SUBI    R0, 1",
            "        STORESP R0, 4",
            "scan_forward_dec_done:",
            "        CMPI    R3, 0",
        ]
    )
    emit_far_branch("BRNZ", "scan_forward_advance", "scan_forward_low")
    lines.extend(["        LOADSP  R0, 4", "        CMPI    R0, 0"])
    emit_far_branch("BRNZ", "scan_forward_advance", "scan_forward_high")
    emit_goto("normal_advance")
    lines.append("")

    lines.append("scan_backward_retreat:")
    lines.extend(
        [
            "        CMPI    R2, 0",
            "        BRNZ    scan_backward_same_byte",
            "        LOADI   R2, 3",
        ]
    )
    emit_load_source_pointer()
    lines.append("        DEC_IDX")
    emit_save_source_pointer()
    emit_goto("scan_backward_fetch")
    lines.extend(
        [
            "scan_backward_same_byte:",
            "        SUBI    R2, 1",
            "scan_backward_fetch:",
        ]
    )
    emit_fetch_token("scan_backward")
    lines.extend(
        [
            "        CMPI    R0, 3",
            "        BRNZ    scan_backward_not_bof",
            "        HALT                    ; unmatched backward scan",
            "scan_backward_not_bof:",
            "        CMPI    R0, 2",
            "        BRNZ    scan_backward_not_eof",
            "        HALT",
            "scan_backward_not_eof:",
            "        CMPI    R0, 1",
            "        BRNZ    scan_backward_open",
            "        ADDI    R3, 1",
            "        BRNC    scan_backward_inc_done",
            "        LOADSP  R0, 4",
            "        ADDI    R0, 1",
            "        STORESP R0, 4",
            "scan_backward_inc_done:",
        ]
    )
    emit_goto("scan_backward_retreat")
    lines.extend(
        [
            "scan_backward_open:",
            "        SUBI    R3, 1",
            "        BRNC    scan_backward_dec_done",
            "        LOADSP  R0, 4",
            "        SUBI    R0, 1",
            "        STORESP R0, 4",
            "scan_backward_dec_done:",
            "        CMPI    R3, 0",
        ]
    )
    emit_far_branch("BRNZ", "scan_backward_retreat", "scan_backward_low")
    lines.extend(["        LOADSP  R0, 4", "        CMPI    R0, 0"])
    emit_far_branch("BRNZ", "scan_backward_retreat", "scan_backward_high")
    emit_goto("dispatch")
    lines.extend(["", "tp_code:"])
    lines.extend(_format_byte_rows(packed))
    lines.append("")
    return "\n".join(lines)


def compile_source(
    source_path: pathlib.Path,
    *,
    max_steps: int = DEFAULT_MAX_STEPS,
) -> tuple[EvaluationResult, str]:
    try:
        text = source_path.read_text(encoding="utf-8")
    except UnicodeDecodeError as exc:
        raise CompileError(f"{source_path}: source is not UTF-8") from exc
    commands, pairs = parse_source(text)
    result = evaluate(commands, pairs, max_steps=max_steps)
    assembly = generate_knot8_assembly(result, source_path.name)
    return result, assembly


def _escaped_output(data: bytes) -> str:
    pieces: list[str] = []
    for value in data:
        if value == 0x0A:
            pieces.append(r"\n")
        elif value == 0x0D:
            pieces.append(r"\r")
        elif value == 0x09:
            pieces.append(r"\t")
        elif 0x20 <= value <= 0x7E and value not in {0x5C, 0x27}:
            pieces.append(chr(value))
        elif value == 0x5C:
            pieces.append(r"\\")
        elif value == 0x27:
            pieces.append(r"\'")
        else:
            pieces.append(f"\\x{value:02x}")
    return "".join(pieces)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Compile deterministic tp2b programs for Knot-8 v4"
    )
    parser.add_argument("source", type=pathlib.Path, help="input .tp file")
    parser.add_argument("-o", "--output", type=pathlib.Path, required=True)
    parser.add_argument("-S", "--assembly", type=pathlib.Path)
    parser.add_argument("-l", "--listing", type=pathlib.Path)
    parser.add_argument(
        "--backend",
        choices=("const", "native", "packed"),
        default="packed",
        help=(
            "packed runs compact 2-bit bytecode on Knot-8 (default); "
            "native expands a specialized CFG; const precomputes output"
        ),
    )
    parser.add_argument(
        "--max-steps",
        type=int,
        default=DEFAULT_MAX_STEPS,
        help=f"compile-time execution limit (default: {DEFAULT_MAX_STEPS})",
    )
    parser.add_argument(
        "--print-output",
        action="store_true",
        help="print the compile-time output as an escaped byte string",
    )
    args = parser.parse_args()

    try:
        if args.backend == "const":
            result, assembly = compile_source(
                args.source, max_steps=args.max_steps
            )
            command_count = result.steps
        else:
            text = args.source.read_text(encoding="utf-8")
            commands, pairs = parse_source(text)
            if args.backend == "native":
                assembly = generate_native_knot8_assembly(
                    commands, pairs, args.source.name
                )
            else:
                assembly = generate_packed_knot8_assembly(
                    commands, args.source.name
                )
            command_count = len(commands)
            result = (
                evaluate(commands, pairs, max_steps=args.max_steps)
                if args.print_output
                else None
            )
        if args.assembly:
            args.assembly.parent.mkdir(parents=True, exist_ok=True)
            args.assembly.write_text(assembly, encoding="utf-8", newline="\n")

        with tempfile.TemporaryDirectory() as directory:
            temporary_assembly = pathlib.Path(directory) / "generated.asm"
            temporary_assembly.write_text(assembly, encoding="utf-8", newline="\n")
            image, listing = assemble(temporary_assembly)

        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_bytes(image)
        if args.listing:
            args.listing.parent.mkdir(parents=True, exist_ok=True)
            args.listing.write_text("\n".join(listing) + "\n", encoding="utf-8")

        if args.backend == "const":
            print(
                f"Compiled {len(result.output)} output bytes after "
                f"{result.steps} tp2b commands -> {len(image)} Knot-8 bytes"
            )
        elif args.backend == "native":
            print(
                f"Compiled {command_count} tp2b commands to native "
                f"Knot-8 FSM/tape execution -> {len(image)} bytes"
            )
        else:
            print(
                f"Compiled {command_count} tp2b commands to packed "
                f"Knot-8 FPGA runtime -> {len(image)} bytes"
            )
        if result is not None and result.terminated_by_unmatched_jump:
            print(
                "warning: canonical interpreter termination was caused by "
                "an unmatched runtime loop scan",
                file=sys.stderr,
            )
        if args.print_output and result is not None:
            print(f"Output: '{_escaped_output(result.output)}'")
        return 0
    except (CompileError, AssemblyError, OSError) as exc:
        print(f"tp2bc: error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
